name: Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  lint:
    if: ${{ !contains(github.event.head_commit.message, '[skip ci]') }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v1
        with:
          node-version: '14.x'
      - uses: bahmutov/npm-install@v1
      - uses: MansaGroup/nrwl-nx-action@v2.1.0
        with:
          targets: lint

  test:
    if: ${{ !contains(github.event.head_commit.message, '[skip ci]') }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v1
        with:
          node-version: '14.x'
      - uses: bahmutov/npm-install@v1
      - uses: MansaGroup/nrwl-nx-action@v2.1.0
        with:
          targets: test

  build:
    if: ${{ !contains(github.event.head_commit.message, '[skip ci]') }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v1
        with:
          node-version: '14.x'
      - uses: bahmutov/npm-install@v1
      - uses: MansaGroup/nrwl-nx-action@v2.1.0
        with:
          targets: build
          args: --prod
      - if: ${{ github.event_name == 'push' }}
        uses: actions/upload-artifact@v2
        with:
          name: build-output
          path: dist

  deploy:
    if: ${{ github.event_name == 'push' && !contains(github.event.head_commit.message, '[skip ci]') }}
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v1
        with:
          node-version: '14.x'
      - uses: bahmutov/npm-install@v1
      - uses: actions/download-artifact@v2
        with:
          name: build-output
      - uses: MansaGroup/nrwl-nx-action@v2.1.0
        with:
          targets: deploy
