name: Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  checks:
    if: ${{ !contains(github.event.head_commit.message, '[skip ci]') }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout git
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: '14.x'
      - name: Install node_modules
        uses: bahmutov/npm-install@v1
      - name: Check files format
        run: yarn format:check --base=origin/main
      - name: Lint & test
        uses: MansaGroup/nrwl-nx-action@v2.1.0
        with:
          targets: lint,test
      - name: Build
        uses: MansaGroup/nrwl-nx-action@v2.1.0
        with:
          targets: build
          args: --prod
      - name: Deploy
        if: ${{ github.event_name == 'push' }} # TODO: also check on commit type, i.e. feat or fix
        uses: MansaGroup/nrwl-nx-action@v2.1.0
        with:
          targets: deploy
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
