name: Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    if: ${{ github.event_name != 'push' || !contains(github.event.head_commit.message, '[skip ci]') }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v1
        with:
          node-version: '14.x'
      - uses: bahmutov/npm-install@v1
      - uses: MansaGroup/nrwl-nx-action@v2.1.0
        with:
          targets: build

  lint:
    if: ${{ github.event_name != 'push' || !contains(github.event.head_commit.message, '[skip ci]') }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v1
        with:
          node-version: '14.x'
      - uses: bahmutov/npm-install@v1
      - uses: MansaGroup/nrwl-nx-action@v2.1.0
        with:
          targets: lint

  test:
    if: ${{ github.event_name != 'push' || !contains(github.event.head_commit.message, '[skip ci]') }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v1
        with:
          node-version: '14.x'
      - uses: bahmutov/npm-install@v1
      - uses: MansaGroup/nrwl-nx-action@v2.1.0
        with:
          targets: test
